os:
  - linux
dist: trusty

sudo: false

env:
  global:
    - ENCRYPTION_LABEL: "82f7c45687fc"
    - COMMIT_AUTHOR_EMAIL: "meiblorn@gmail.com"

addons:
  apt:
    packages:
      - google-chrome-stable
      - tree

  code_climate:
    repo_token:
      secure: d703bbnywJZBYOllybVPlUfJGh6QTulz+NGrQsjx+wxhl5a6cJaqKofxOUmUbZMYqWyodYrR685iYridhXLCF3bqO3Sfacm46Jdjhc4gxTE3Y5/MlVMV9syR6+1PLLCSsFTNcJmhyOM6+MmJMUZQgAv+lyXHHqA+v9qg9LfFj10bJF8eWDpi7Mjbyhe72o2FR2OVHy0B2FEClls0lkdnfhOdNBANiAYoZtJiwPXsxi521NdMg82gNyTMKoMmKimgXbSg7mjWqGzgqktmFtRctuBUxsyl/vVN5zfqbgS8rfqzHw2WpYuvWbW2sIIrB4iqlXqeXkOFkrYO8axenrSkAtgsGFf36xV33/vVXFxLYR2S7bl5GcnehqdGs3WgXv2c32CGoRzMocZAMf25/RhdvlCrKrOgobkUvwnT5dmyAL6jHowMzQJuf+tuFHeJEBuhFbcOHxrSvLYjnzKrq5p2Sz9+qtesraFUh72WuehKba9hjc7L96zuuT55qfxgSPIn/hC11F1mqs5yImyGzrpXG7BYaUg6Gmrnn9vuWio2jTSx+mWhhAi3/YCq9mZK0uBolVoz6anOWz3VNvQD08+WfYfKAnNG4CCc0ez+klTn05VlMXSZbNUosiSym+INHooKtAQR4GdHAp1rRwaGRn0EoPjSC1xHOwDHcfyfdky6T28=

git:
  depth: 5

branches:
  except:
    - gh-pages

language: node_js
node_js:
  - stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm install

script:
  - npm run ci
  - npm run build:release

after_success:
  - chmod -R a+x scripts
  - bash ./scripts/git/gh-pages.sh
  - bash ./scripts/npm/publish.sh
  - bash ./scripts/npm/codeclimate.sh
